spring.application.name=arlbackend
spring.datasource.url=jdbc:mysql://localhost:3308/arl_db
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=NEJnej1015
=======
spring.datasource.password=Tan88200.
>>>>>>> feature/add-new-book-modification

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
